### ISSUE TITLE
Add de-ripple key/value pairs to subfile

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/mwax_udp2sub#4]
### Input
* mwax_u2s reads a [Metafits file](https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24969594/Metafits+files) for each 8 second subobservation file it attempts to create. There are already some things read from the metafits file already. This issue is to read another contains 2 keys we care about and put them into the subfile header:
  * Extra metafits keys to read:
    * DR_FLAG (bit 0 | 1)
    * DR_PARAM (string e.g. "deripplev1")

### Output
* When writing the [subfile PSRDADA header](https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24970579/MWAX+PSRDADA+header), write out:
  * APPLY_COARSE_DERIPPLE (bit 0|1 based on DR_FLAG from metafits)
  * DR_PARAM (based on DR_PARAM from metafits)

### Note
* This issue has been partly implemented in the [oversampling-static branch](https://github.com/MWATelescope/mwax_udp2sub/compare/master...oversampling-static)

### Documentation
* Update wiki page [MWAX PSRDADA header](https://mwatelescope.atlassian.net/wiki/spaces/MP/pages/24970579/MWAX+PSRDADA+header)

**Comment by shrydar** [comment]
DERIPPLE flag read from metafits file and written out as APPLY_COARSE_DERIPPLE to subfile header as per oversampling-static branch, cf https://github.com/MWATelescope/mwax_udp2sub/commit/f14572ec591a7cebac0a2518cb3fb6f22bc6dac3

DR_FLAG is to be deprecated, and DR_PARAM doesn't need to be passed through - we'll only ever have one set of deripple parameters in play, and they're unlikely to change (though they may end up being receiver dependent).
