### ISSUE TITLE
Add oversampling command line argument

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/mwax_udp2sub#5]
### Introduction
The MWA's 16 RRI receivers are only capable of producing 1.28 MHz wide coarse channels. These coarse channels, just by way of how the PFB / FFT works end up with a power drop off at the edges of the channel. A way of getting around this is to oversample the coarse channels. That is you make the receivers create wider channels (in this case they are 1.6384 MHz wide), meaning they overlap the previous and next coarse channels by some amount. In MWA's case, only the next-gen receivers are capable of this (NI, SHAO at time of writing). At some point there will be enough next-gen receivers to allow oversampling of enough tiles to make it worthwhile. When u2s gets the 1.6384 MHz wide channel it will do it's normal job and write a subfile. 

This wiki article shows the differences between the critically sampled (1.28 MHz) packets and the oversampled packets: [UDP Packet Structure](https://mwatelescope.atlassian.net/wiki/spaces/MWAOPS/pages/24379717/UDP+Packet+Structure)

### Changes
* This change was hard coded for a test in 2023 in the [oversampling-static branch](https://github.com/MWATelescope/mwax_udp2sub/compare/master...oversampling-static).
* This needs to be incorporated as a command line argument to mwax_u2s. i.e. could be a flag. If present, oversampling is ON. If not present oversampling is off (i.e. default behaviour of 1.28 MHz channels).
* The idea would be that we would reconfigure the MWA between critically sampled and oversampled mode (i.e. stop correlator, restart correlator).
* There is a **mwax.cfg** config file (see: [MWAX Configuration)](https://mwatelescope.atlassian.net/wiki/spaces/MWAOPS/pages/24382825/MWAX+Configuration) which has an oversamping flag that tells M&C to create specific sized subfiles and ringbuffers on start of the correlator. @andreww5au could you use this mechanism to pass the appropriate command line flag to mwax_u2s? NOTE: currrently mwax_u2s does not read that config file. And in this case we wouldn't want to change oversampled mode at runtime anyway.
* So on startup, based on the command line arg, it would be in critical sampling mode or oversampling mode.
* Note the different packet type (0x20 for critically sampled and 0x30 for oversampled). I think, if u2s detects a conflict between the packet type and the command line arg, it should exit gracefully with an appropriate error message. That way if this happens in prod we will know immediately.

**Comment by shrydar** [comment]
Implemented by reading the oversampling flag from mwax.cfg directly, cf
https://github.com/MWATelescope/mwax_udp2sub/commit/05e91c35b8285db2876b6aa4b3c6dba20559cd1e
and
https://github.com/MWATelescope/mwax_udp2sub/commit/ed9beef57a57c0b20fe380b9ef8508fb5d8e9ec7

(the latter to fix a bug where the now-dynamically allocated packet buffers were being discarded when a slot was cleared for reuse)
